@startuml

class RegisterUseCase {
  - usersRepository: UsersRepository
  + execute(name: string, email: string, password: string): Promise<RegisterUseCasesResponse>
}

class UsersRepository {
  + findByEmail(email: string): Promise<User>
  + create(name: string, email: string, password_hash: string): Promise<User>
}

interface  RegisterUseCasesRequest {
  - name: string
  - email: string
  - password: string
}

Interface RegisterUseCasesResponse {
  - user: User
}

class User {
  - name: string
  - email: string
  - password_hash: string
}

RegisterUseCase --> UsersRepository
RegisterUseCasesRequest --> RegisterUseCases
RegisterUseCasesResponse --> User

@enduml
